# Generated by Django 2.2.12 on 2020-08-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='pic',
            field=models.ImageField(default='static/img/ProfilePic.jpg', upload_to='static/img'),
        ),
    ]
