# Generated by Django 2.2.12 on 2020-08-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_cv_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=150)),
                ('date', models.DateField()),
            ],
        ),
    ]
