# Generated by Django 2.2.12 on 2020-08-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
